# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "白蘋果急救室 2.0"
email: kouko.d@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: kouko_d
github_username:  kouko

# Pagenation
paginate: 9
paginate_path: /post/page:num  # Setting Post Pagenation URL

# Build settings
markdown: kramdown
permalink: /post/:year/:month/:slug # Setting Post URL

# Custom settings
encoding: utf-8

#Archive
jekyll-archives:
  enabled: [categories]
  layout: 'archive'
  permalinks:
    category: '/post/category/:name/'


# Gems
gems: [jekyll-paginate, jekyll-archives]
